spring:
  application:
    name: bradesco
  cloud:
    openfeign:
      client:
        config:
          bloqueioCartao:
            url: "${BLOQUEIO_SERVICE_BASE_URL:http://localhost:8081}"
            connectTimeout: 3000
            readTimeout: 5000

server:
  port: 8080
  servlet:
    context-path: /bff

logging:
  level:
    root: INFO
    br.com.empresa.bff: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger - %msg%n"

bloqueio-cartao:
  path: "${BLOQUEIO_SERVICE_PATH:/api/v1/bloqueios-cartao}"

okhttp-configuracao-geral:
  write-timeout-millis: 5000
  retryOnConnectionFailure: true

okhttp-connection-pool:
  max-idle-connections: 20
  keep-alive-duration-segundos: 60

okhttp-dispatcher:
  max-requests: 64
  max-requests-per-host: 5
